# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-eventbrite-extension}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gerrit Kaiser"]
  s.date = %q{2011-02-13}
  s.description = %q{Provides a few Radius Tags to access data from the EventBrite API}
  s.email = %q{gerrit@gerritkaiser.de}
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "README.mdown",
    "Rakefile",
    "VERSION",
    "app/models/eventbrite_tags.rb",
    "eventbrite_extension.rb"
  ]
  s.homepage = %q{http://ext.radiantcms.org/extensions/265-eventbrite}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Eventbrite Extension for Radiant CMS}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventbright>, ["~> 0.2.3"])
    else
      s.add_dependency(%q<eventbright>, ["~> 0.2.3"])
    end
  else
    s.add_dependency(%q<eventbright>, ["~> 0.2.3"])
  end
end

